name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1.3.2
      - name: Install dependencies
        run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - name: Run tests
        run: flutter test
